#pragma once

class Addresses {

public:

	enum CHARLIST_OFFSET {
		CHARLIST_OFFSET_CHAR_NAME = 0x4,
		CHARLIST_OFFSET_WORLD = 0x4E,
		CHARLIST_OFFSET_INDEX = 0x9CF07C,
		CHARLIST_OFFSET_START = 0x9CF020,
		CHARLIST_OFFSET_END = 0x9CF024
	};

	enum BATTLELIST_OFFSET {
		BATTLELIST_OFFSET_START = 0xA29690,
		BATTLELIST_OFFSET_STEP = 0xDC,
		BATTLELIST_OFFSET_ENTRIES = 0x513,
		BATTLELIST_OFFSET_END = BATTLELIST_OFFSET_START + (BATTLELIST_OFFSET_STEP * BATTLELIST_OFFSET_ENTRIES),
		BATTLELIST_OFFSET_DistanceId = 0,
		BATTLELIST_OFFSET_DistanceType = 3,
		BATTLELIST_OFFSET_DistanceName = 4,
		BATTLELIST_OFFSET_DistanceX = 44,
		BATTLELIST_OFFSET_DistanceY = 40,
		BATTLELIST_OFFSET_DistanceZ = 36,
		BATTLELIST_OFFSET_DistanceIsWalking = 80,
		BATTLELIST_OFFSET_DistanceDirection = 84,
		BATTLELIST_OFFSET_DistanceOutfit = 96,
		BATTLELIST_OFFSET_DistanceAddon = 116,
		BATTLELIST_OFFSET_DistanceMountId = 120,
		BATTLELIST_OFFSET_DistanceIsVisible = 172,
		BATTLELIST_OFFSET_DistanceSkull = 152,
		BATTLELIST_OFFSET_DistanceColorHead = 100,
		BATTLELIST_OFFSET_DistanceColorBody = 104,
		BATTLELIST_OFFSET_DistanceColorLegs = 108,
		BATTLELIST_OFFSET_DistanceColorFeet = 112,
		BATTLELIST_OFFSET_DistanceWarIcon = 168,
		BATTLELIST_OFFSET_DistanceWalkSpeed = 144,
		BATTLELIST_OFFSET_DistanceHPBar = 140
	};

	enum PLAYER_OFFSET {
		PLAYER_OFFSET_ID = 0xA2976C,
		PLAYER_OFFSET_XOR = 0x834D70,
		PLAYER_OFFSET_HP = 0x9D2000,
		PLAYER_OFFSET_MAX_HP = 0x9D202C,
		PLAYER_OFFSET_MANA = 0x834DC4,
		PLAYER_OFFSET_MAX_MANA = 0x834D74
	};

};